GET http://localhost:3000/toto HTTP/1.1

###

# route pour récupérer tous les films

GET http://localhost:3000/movie HTTP/1.1

###

POST http://localhost:3000/movie HTTP/1.1
content-type: application/json

{
    "name": "Conan The Barbarian"
}

###

POST http://localhost:3000/movie HTTP/1.1
content-type: application/json

{
    "name": "Metropolis"
}